language: csharp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - llvm-3.8-dev
            - clang-3.8
            - libgc-dev

    # OS X build won't find libLLVM.dylib for some reason.
    # I'd love to get flame-llvm to work on OS X, but I don't own a computer with
    # OS X on it and debugging Travis builds without a machine running
    # the same OS is pretty hard.
    # Giving up on this now, might revisit it later.
    # - os: osx

install:
  # Install homebrew packages if we're running on OS X
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install llvm;
      brew install libgc;
      export readlink_name="greadlink";
      export libllvm_path="/usr/local/opt/llvm/lib/libLLVM.dylib";
    else
      export readlink_name="readlink";
      export libllvm_path="/usr/lib/llvm-3.8/lib/libLLVM.so";
    fi

  # Compile LLVMSharp
  - ./build-libs.sh $libllvm_path
script:
  # Restore NuGet packages
  - nuget restore flame-llvm.sln
  # Build the project with the reference C# compiler
  - msbuild /p:Configuration=Release flame-llvm.sln
  # Build the project with ecsc
  - make all

  # Build the runtime and stdlib
  - make stdlib

  # Run the test suite
  - make test
